
--[[ BASE MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.BASE_MODULE_ENABLED = true
    GlorifiedLeveling.Config.XPGain.BASE_MODULE_SETTINGS = {
        TIMER_REWARD = true,
        TIMER_TIME = 120,
        TIMER_AMOUNT = 75,

        KILL_REWARD = true,
        KILL_AMOUNT = 50,

        NPC_KILL_REWARD = true,
        NPC_KILL_AMOUNT = 20,
    }
--[[ BASE MODULE SETTINGS END ]]--

--[[ DARKRP MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.DARKRP_MODULE_ENABLED = true
    GlorifiedLeveling.Config.XPGain.DARKRP_MODULE_SETTINGS = {
        SALARY_REWARD = true,
        SALARY_AMOUNT = 15,

        LOTTO_REWARD = true,
        LOTTO_AMOUNT = 200,

        ARREST_REWARD = true,
        ARREST_AMOUNT = 100,

        HIT_REWARD = true,
        HIT_AMOUNT = 100,
    }
--[[ DARKRP MODULE SETTINGS END ]]--

--[[ TTT MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.TTT_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.TTT_MODULE_SETTINGS = {
        ROUND_WON_REWARD = true,
        ROUND_WON_AMOUNT = 35,

        TRAITOR_KILLED_REWARD = true,
        TRAITOR_KILLED_AMOUNT = 100,

        INNOCENT_KILLED_AS_TRAITOR_REWARD = true,
        INNOCENT_KILLED_AS_TRAITOR_AMOUNT = 25,

        DETECTIVE_KILLED_AS_TRAITOR_REWARD = true,
        DETECTIVE_KILLED_AS_TRAITOR_AMOUNT = 75,
    }
--[[ TTT MODULE SETTINGS END ]]--

--[[ MURDER MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.MURDER_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.MURDER_MODULE_SETTINGS = {
        ROUND_WON_REWARD = true,
        ROUND_WON_AMOUNT = 35,

        MURDERER_KILLED_REWARD = true,
        MURDERER_KILLED_AMOUNT = 100,

        INNOCENT_KILLED_REWARD = true,
        INNOCENT_KILLED_AMOUNT = 50,
    }
--[[ MURDER MODULE SETTINGS END ]]--

--[[ CRAP-HEAD'S ADDONS MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.CRAP_HEAD_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.CRAP_HEAD_MODULE_SETTINGS = {
        BITMINER_WITHDRAW_REWARD = true,
        BITMINER_WITHDRAW_REWARD_MULTIPLIER = 0.1,

        CHOPSHOP_VEHICLE_SCRAPPED_REWARD = true,
        CHOPSHOP_VEHICLE_SCRAPPED_REWARD_AMOUNT = 100,

        BANK_ROBBERY_SUCCESS_REWARD = true,
        BANK_ROBBERY_SUCCESS_REWARD_AMOUNT = 500,

        SUPPLY_CRATE_ROBBERY_SUCCESS_REWARD = true,
        SUPPLY_CRATE_ROBBERY_SUCCESS_REWARD_AMOUNT = 500,

        CHRISTMAS_PRESENT_OPENED_REWARD = true,
        CHRISTMAS_PRESENT_OPENED_REWARD_AMOUNT = 200,
    }
--[[ CRAP-HEAD'S ADDONS MODULE SETTINGS END ]]--

--[[ ONEPRINT'S MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.ONEPRINT_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.ONEPRINT_MODULE_SETTINGS = {
        PRINTER_WITHDRAWAL_REWARD = true,
        PRINTER_WITHDRAWAL_MULTIPLIER = 0.1
    }
--[[ ONEPRINT'S ADDONS MODULE SETTINGS END ]]--

--[[ ONEPRINT'S MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.ONEPRINT_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.ONEPRINT_MODULE_SETTINGS = {
        PRINTER_WITHDRAWAL_REWARD = true,
        PRINTER_WITHDRAWAL_MULTIPLIER = 0.1
    }
--[[ ONEPRINT'S ADDONS MODULE SETTINGS END ]]--

--[[ SPRINTER'S MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.SPRINTER_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.SPRINTER_MODULE_SETTINGS = {
        PRINTER_WITHDRAWAL_REWARD = true,
        PRINTER_WITHDRAWAL_MULTIPLIER = 0.1
    }
--[[ SPRINTER'S ADDONS MODULE SETTINGS END ]]--

--[[ BKEYPAD'S MODULE SETTINGS ]]--
    GlorifiedLeveling.Config.XPGain.BKEYPAD_MODULE_ENABLED = false
    GlorifiedLeveling.Config.XPGain.BKEYPAD_MODULE_SETTINGS = {
        KEYPAD_CRACKED_REWARD = true,
        KEYPAD_CRACKED_REWARD_AMOUNT = 100
    }
--[[ BKEYPAD'S ADDONS MODULE SETTINGS END ]]--